<?php

class Vtiger_Browse_File extends Vtiger_Basic_File
{
	public $storageName = 'MultiImage';

	/**
	 * File type.
	 *
	 * @var string
	 */
	public $fileType = 'image';

	public function getCheckPermission(\App\Request $request)
	{
		//return parent::getCheckPermission($request); // TODO: Change the autogenerated stub
		return true;
	}

	/**
	 * View image.
	 *
	 * @param \App\Request $request
	 *
	 * @throws \App\Exceptions\AppException
	 * @throws \App\Exceptions\IllegalValue
	 * @throws \App\Exceptions\NoPermitted
	 */
	public function get(\App\Request $request)
	{
		if ($request->isEmpty('key', 2)) {
			throw new \App\Exceptions\NoPermitted('Not Acceptable', 406);
		}
		$recordModel = Vtiger_Record_Model::getInstanceById($request->getInteger('record'), $request->getModule());
		$key = $request->getByType('key', 2);
		App\DebugerEx::log('Vtiger_Browse_File', $key);

		$fileP = "storage/test/2018/December/week1/{$key}";

		header('Pragma: public');
		header('Cache-Control: max-age=86400, public');
		header('Expires: ' . gmdate('D, d M Y H:i:s \G\M\T', time() + 86400));
		header('Content-Type: ' . 'image');
		header('Content-Transfer-Encoding: binary');
		header('Content-length: ' . filesize($fileP));
		readfile($fileP);
		return;
		/*$file = \App\Fields\File::loadFromInfo([
			'path' => ROOT_DIRECTORY . DIRECTORY_SEPARATOR . $item['path'],
			'name' => $item['name'],
		]);*/

		$value = \App\Json::decode($recordModel->get($request->getByType('field', 2)));
		foreach ($value as $item) {
			if ($item['key'] === $key) {
				$file = \App\Fields\File::loadFromInfo([
					'path' => ROOT_DIRECTORY . DIRECTORY_SEPARATOR . $item['path'],
					'name' => $item['name'],
				]);
				header('Pragma: public');
				header('Cache-Control: max-age=86400, public');
				header('Expires: ' . gmdate('D, d M Y H:i:s \G\M\T', time() + 86400));
				header('Content-Type: ' . $file->getMimeType());
				header('Content-Transfer-Encoding: binary');
				header('Content-length: ' . $file->getSize());
				if ($request->getBoolean('download')) {
					header('Content-disposition: attachment; filename="' . $item['name'] . '"');
				}
				readfile($file->getPath());
			}
		}
	}
}
